[package]
name = "fluentbase-contracts-webauthn"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = { version = "0.22.0", default-features = false, features = ["alloc"] }
fluentbase-sdk = { workspace = true }
hex = { version = "0.4", default-features = false, features = ["alloc"] }
# p256 = {version = "0.13.2", default-features = false, features = ["ecdsa", "arithmetic"]}
revm-precompile = { workspace = true }
sha2 = { version = "0.10", default-features = false }

[dev-dependencies]
fluentbase-testing = { workspace = true }
p256 = { version = "0.13.2", default-features = false, features = [
    "ecdsa",
    "arithmetic",
] }

[lib]
crate-type = ["cdylib"]
path = "lib.rs"

[features]
default = ["std"]
std = [
    "fluentbase-sdk/std", #   "p256/std",
    "sha2/std",
    "base64/std",
    "hex/std",
    "revm-precompile/std",
    "fluentbase-testing/std",
]
fluent-testnet = [
    "fluentbase-sdk/fluent-testnet",
    "fluentbase-testing/fluent-testnet"
]
