edition = "2021"
group_imports = "One"
ignore = ["revm/*"]
imports_granularity = "Crate"
#imports_layout = "HorizontalVertical"

comment_width = 100
max_width = 100
newline_style = "Unix"
normalize_comments = false
reorder_imports = true
unstable_features = true
wrap_comments = false