[package]
edition = "2021"
name = "fluentbase-examples-secp256k1"
version = "0.1.0"

[dependencies]
fluentbase-sdk = { workspace = true }
libsecp256k1 = { version = "0.7.1", default-features = false, features = [
    "static-context",
    "hmac",
] }
#secp256k1 = { version = "0.30.0", default-features = false, features = ["recovery", "alloc"] }
secp256k1-sys = { version = "0.10.1", default-features = false, features = [
    "alloc",
    "recovery",
] }

[dev-dependencies]
tiny-keccak = { workspace = true }
hex = "0.4.3"
hex-literal = "1.0.0"
fluentbase-testing = { workspace = true }

[lib]
crate-type = ["cdylib"]
path = "lib.rs"

[features]
default = ["std"]
std = ["fluentbase-sdk/std", "fluentbase-testing/std"]
fluent-testnet = [
    "fluentbase-sdk/fluent-testnet",
    "fluentbase-testing/fluent-testnet"
]
testing-enabled = []
