[package]
name = "fluentbase-rwasm-evm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
bench = false
proc-macro = false

[dependencies]
fluentbase-rwasm-code-snippets = { workspace = true, default-features = false }
rwasm = { workspace = true, features = ["std"] }
fluentbase-sdk = { workspace = true }
fluentbase-codec = { workspace = true }
alloy-primitives = { workspace = true, default-features = false }
hashbrown = { workspace = true }
bitvec = { version = "1", default-features = false, features = ["alloc"] }
fluentbase-types = { workspace = true, default-features = false }

[dev-dependencies]
fluentbase-runtime = { workspace = true }
env_logger = { version = "0.10.2" }
log = { version = "0.4.20" }
ctor = "0.2.6"
keccak-hash = "0.10.0"
lazy_static = { workspace = true }

[build-dependencies]
hex = { version = "0.4", default-features = false }

[features]
default = ["no_gas_measuring"]
no_gas_measuring = []
