[package]
name = "fluentbase-contracts-secp256r1"
version = "0.1.0"
edition = "2021"

[dependencies]
fluentbase-sdk = { workspace = true }
sha2 = { version = "0.10", default-features = false }

[dev-dependencies]
fluentbase-sdk-testing = { workspace = true }
hex = "0.4.3"
p256 = { version = "0.13.2", default-features = false, features = [
    "ecdsa",
    "arithmetic",
] }
sha2 = { version = "0.10", default-features = false }

[lib]
crate-type = ["cdylib"]
path = "lib.rs"

[features]
default = ["std"]
std = ["fluentbase-sdk/std"]
