[package]
name = "fluentbase-examples-svm-solana-program-state-usage"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/solana_program.rs"

[dependencies]
fluentbase-examples-svm-bindings = { path = "../bindings" }
fluentbase-svm-shared = { path = "../../../../crates/svm-shared" }

solana-pubkey = { git = "https://github.com/anza-xyz/agave", tag = "v2.1.18", default-features = false }
solana-account-info = { git = "https://github.com/anza-xyz/agave", tag = "v2.1.18", default-features = false }
solana-program-entrypoint = { git = "https://github.com/anza-xyz/agave", tag = "v2.1.18", default-features = false }
solana-program-error = { git = "https://github.com/anza-xyz/agave", tag = "v2.1.18", default-features = false }
solana-msg = { git = "https://github.com/anza-xyz/agave", tag = "v2.1.18", default-features = false }
solana-program = { git = "https://github.com/anza-xyz/agave", tag = "v2.1.18", default-features = false }
solana-sdk = { git = "https://github.com/anza-xyz/agave", tag = "v2.1.18", default-features = false }

spl-token = { git = "https://github.com/solana-labs/solana-program-library", tag = "token-client-v0.13.0" }

num-traits = { version = "0.2.19", default-features = false, features = [] }
num-derive = { version = "0.4.2", default-features = false, features = [] }
libsecp256k1 = "0.7.2"

[build-dependencies]
cargo_metadata = "0.19"

[profile.dev]
panic = "abort"
lto = true
opt-level = 3
strip = true
debug = false
debug-assertions = false
rpath = false
codegen-units = 1

[profile.release]
panic = "abort"
lto = true
opt-level = 3
strip = true
debug = false
debug-assertions = false
rpath = false
codegen-units = 1

