[package]
name = "fluentbase-examples-svm-solana-program-state-usage"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/solana_program.rs"

[dependencies]
fluentbase-examples-svm-bindings = { path = "../bindings" }

solana-pubkey = { git = "https://github.com/anza-xyz/agave", tag = "v2.1.18", default-features = false }
solana-account-info = { git = "https://github.com/anza-xyz/agave", tag = "v2.1.18", default-features = false }
solana-program-entrypoint = { git = "https://github.com/anza-xyz/agave", tag = "v2.1.18", default-features = false }
solana-program-error = { git = "https://github.com/anza-xyz/agave", tag = "v2.1.18", default-features = false }
solana-msg = { git = "https://github.com/anza-xyz/agave", tag = "v2.1.18", default-features = false }
solana-program = { git = "https://github.com/anza-xyz/agave", tag = "v2.1.18", default-features = false }
solana-sdk = { git = "https://github.com/anza-xyz/agave", tag = "v2.1.18", default-features = false }
num-traits = { version = "0.2.19", default-features = false, features = [] }
num-derive = { version = "0.4.2", default-features = false, features = [] }
bincode = "1.3.3"
hex = "0.4.3"
hex-literal = "0.4.1"
libsecp256k1 = "0.7.2"

[profile]

