[package]
name = "fluentbase-universal-token"
version.workspace = true
authors.workspace = true
repository.workspace = true
edition.workspace = true
readme.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
fluentbase-sdk = { workspace = true, features = [
    #    "fast-panic",
    #    "debug-print"
] }


bincode = { workspace = true, default-features = false, features = ["serde"] }
hashbrown = { workspace = true, default-features = false }
spin = { workspace = true }
paste = { workspace = true }

[dev-dependencies]

[features]
default = [
    "std",
]
std = []
debug-print = []
fluent-testnet = [
    "fluentbase-sdk/fluent-testnet",
]
