[alias]
clippy-ci = "clippy --workspace --all-targets --all-features -- -D warnings"
clippy-ci-contracts = "clippy --manifest-path=./contracts/Cargo.toml --workspace --all-targets --all-features -- -D warnings"
clippy-ci-examples = "clippy --manifest-path=./examples/Cargo.toml --workspace --all-targets --all-features -- -D warnings"

clippy-ci-fast = "clippy --workspace --all-targets -- -D warnings"
clippy-ci-fast-contracts = "clippy --manifest-path=./contracts/Cargo.toml --workspace --all-targets -- -D warnings"
clippy-ci-fast-examples = "clippy --manifest-path=./examples/Cargo.toml --workspace --all-targets -- -D warnings"
