[package]
name = "fluentbase-examples-json"
version = "0.1.0"
edition = "2021"

[dependencies]
fluentbase-sdk = { workspace = true }
serde = { workspace = true }
serde-json-core = { version = "0.6.0" }

[dev-dependencies]
fluentbase-testing = { workspace = true }
serde_json = "1.0"

[lib]
crate-type = ["cdylib"]
path = "lib.rs"

[features]
default = ["std"]
std = ["fluentbase-sdk/std"]
