[package]
name = "fluentbase-evm"
version.workspace = true
authors.workspace = true
repository.workspace = true
edition.workspace = true
readme.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
fluentbase-sdk = { workspace = true }
fluentbase-types = { workspace = true }
bitvec = { workspace = true }
bincode = { workspace = true }

# revm
revm-primitives = { workspace = true }
revm-bytecode = { workspace = true }
revm-interpreter = { workspace = true }
revm-context = { workspace = true }
revm-helpers = { workspace = true }
serde = { version = "1.0.228", default-features = false, features = ["derive"] }

[features]
default = ["std"]
std = [
    "fluentbase-sdk/std",
    "revm-primitives/std",
    "revm-bytecode/std",
    "revm-interpreter/std",
    "revm-context/std",
]
serde = [
    "revm-interpreter/serde",
    "fluentbase-sdk/serde"
]
