[package]
name = "fluentbase-evm"
version.workspace = true
authors.workspace = true
repository.workspace = true
edition.workspace = true
readme.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
# fluentbase
fluentbase-sdk = { workspace = true }
# misc
bitvec = { workspace = true }
bincode = { workspace = true }
serde = { workspace = true }
once_cell = { workspace = true }
# revm
revm-primitives = { workspace = true }
revm-bytecode = { workspace = true }
revm-interpreter = { workspace = true }
revm-context = { workspace = true }
revm-context-interface = { workspace = true }

[features]
default = ["std"]
std = [
    "fluentbase-sdk/std",
    "revm-primitives/std",
    "revm-bytecode/std",
    "revm-interpreter/std",
    "revm-context/std",
]
serde = [
    "revm-interpreter/serde",
    "fluentbase-sdk/serde"
]
debug-print = [
    "fluentbase-sdk/debug-print",
    "revm-interpreter/debug-print",
]
# We have it to silent warnings inside macroses
memory_limit = []