[package]
name = "fluentbase-evm"
version.workspace = true
authors.workspace = true
repository.workspace = true
edition.workspace = true
readme.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
fluentbase-sdk = { workspace = true }
bitvec = { workspace = true }
bincode = { workspace = true }

[dev-dependencies]
fluentbase-sdk-testing = { workspace = true }

[features]
default = ["std"]
std = [
    "fluentbase-sdk/std",
]
json = [
	"fluentbase-sdk/json",
	"fluentbase-sdk-testing/json"
]
