[package]
name = "fluentbase-sdk-derive-core"

authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true

readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
alloy-sol-macro-input = { version = "1.1.0", default-features = false }
anyhow.workspace = true
convert_case = "0.8.0"
crypto-hashes = { version = "0.10.0", default-features = false, features = ["include_weak"] }
darling = "0.20.10"
fluentbase-codec = { workspace = true }
hex = "0.4.3"
proc-macro-error = { version = "1", default-features = false }
proc-macro2 = "1.0"
quote = "1.0"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = "1.0"
syn = { workspace = true, features = ["full", "visit"] }
syn-solidity = { version = "1.1.0", default-features = false, features = ["visit"] }
thiserror = "2.0.12"
tracing = { version = "0.1.40", default-features = false }

[dev-dependencies]
bytes = "1.0"
insta = { version = "1.43.1", features = ["yaml"] }
prettyplease = "0.2.32"

[features]
default = []
json = ["alloy-sol-macro-input/json"]
