[package]
name = "fluentbase-examples-tiny-keccak"
version = "0.1.0"
edition = "2021"

[dependencies]
fluentbase-sdk = { workspace = true }
tiny-keccak = { workspace = true }

[dev-dependencies]
fluentbase-sdk-testing = { workspace = true }

[build-dependencies]
fluentbase-build = { workspace = true }
fluentbase-sdk = { workspace = true }
tiny-keccak = { workspace = true }

[features]
default = ["std"]
std = ["fluentbase-sdk/std"]
