[package]
name = "fluentbase-examples-rwasm"
version = "0.1.0"
edition = "2021"

[dependencies]
fluentbase-sdk = { workspace = true }
rwasm = { workspace = true }

[build-dependencies]
fluentbase-build = { workspace = true }
fluentbase-sdk = { workspace = true }
rwasm = { workspace = true }

[features]
default = ["std"]
std = ["fluentbase-sdk/std", "rwasm/std"]
