# Publishes the Docker image.

name: Docker (Fluent)

on:
  push:
    tags:
      - v*

env:
  IMAGE_NAME: ${{ github.repository_owner }}/fluent
  CARGO_TERM_COLOR: always
  DOCKER_IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/fluent
  DOCKER_USERNAME: ${{ github.actor }}
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  build-rc:
    if: contains(github.ref, '-rc')
    name: build and push as release candidate
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: "Build and push fluent image"
            command: "make IMAGE_NAME=$IMAGE_NAME DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME PROFILE=maxperf docker-build-push"
    steps:
      - uses: actions/checkout@v6
      - uses: rui314/setup-mold@v1
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Install cross main
        id: cross_main
        run: |
          cargo +1.92.0 install cross --git https://github.com/cross-rs/cross
      - name: Log in to Docker
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io --username ${DOCKER_USERNAME} --password-stdin
      - name: Set up Docker builder
        run: |
          docker run --privileged --rm tonistiigi/binfmt --install arm64,amd64
          docker buildx create --use --name cross-builder
      - name: Build and push ${{ matrix.build.name }}
        run: ${{ matrix.build.command }}

  build:
    if: ${{ !contains(github.ref, '-rc') }}
    name: build and push as latest
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: "Build and push fluent image"
            command: "make IMAGE_NAME=$IMAGE_NAME DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME PROFILE=maxperf docker-build-push-latest"
    steps:
      - uses: actions/checkout@v6
      - uses: rui314/setup-mold@v1
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Install cross main
        id: cross_main
        run: |
          cargo +1.92.0 install cross --git https://github.com/cross-rs/cross
      - name: Log in to Docker
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io --username ${DOCKER_USERNAME} --password-stdin
      - name: Set up Docker builder
        run: |
          docker run --privileged --rm tonistiigi/binfmt --install arm64,amd64
          docker buildx create --use --name cross-builder
      - name: Install clang and build tools
        run: |
          sudo apt-get update && sudo apt-get install -y libclang-dev pkg-config
      - name: Build and push ${{ matrix.build.name }}
        run: ${{ matrix.build.command }}
